Repository DDD-Community/DDD-10-KKEUNKKEUN-WEB, pull requests merged in 2024-03, with the labels that each got.

#38 소켓 로직 구현
  package-lock.json
  package.json
  src/app/(afterlogin)/socket-test/page.tsx
  src/services/client/user.ts
  src/types/service.ts
Labels: ✨FEAT

#39 발표 연습 페이지 헤더 이벤트 처리 및 조회 API 연동
  src/app/(afterlogin)/practice/[id]/page.module.scss
  src/app/(afterlogin)/practice/[id]/page.tsx
  src/app/(afterlogin)/practice/_components/PracticeNav.module.scss
  src/app/(afterlogin)/practice/_components/PracticeNav.tsx
  src/app/(afterlogin)/practice/_components/Recorder.tsx
  src/app/(afterlogin)/practice/_hooks/useRecorder.ts
  src/app/(afterlogin)/practice/_svgs/RecordIcon.tsx
  src/app/(afterlogin)/practice/_svgs/RecordOnIcon.tsx
  src/app/(afterlogin)/practice/layout.tsx
  src/app/(afterlogin)/setting/[id]/_components/SettingNav.tsx
  src/app/_components/_modules/SpeechBubble.tsx
  src/app/_components/_modules/_modal/Modal.tsx
  src/app/_svgs/CloseIcon.tsx
  src/app/_svgs/CloseIconWhite.tsx
  src/services/client/practice.ts
  src/types/service.ts
Labels: ♻️REFACTOR, ✨FEAT

#41 발표 수정 및 추가 페이지 입력 값 업데이트 누락 문제 해결
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.tsx
Labels: 🐛FIX

#42 날짜 오류 수정
  src/app/(afterlogin)/upload/[id]/_component/UploadDeadlineDate.tsx
Labels: 🐛FIX

#44 최초 사용자 전용 모달 생성
  src/app/(afterlogin)/home/_components/GuideContent.module.scss
  src/app/(afterlogin)/home/_components/GuideContent.tsx
  src/app/(afterlogin)/home/_components/GuideForNew.tsx
  src/app/(afterlogin)/home/_components/_svgs/OneIcon.tsx
  src/app/(afterlogin)/home/_components/_svgs/ThreeIcon.tsx
  src/app/(afterlogin)/home/_components/_svgs/TwoIcon.tsx
  src/app/(afterlogin)/home/page.tsx
Labels: ✨FEAT

#46 미들웨어 인증 기반 path조건 추가
  src/middleware.ts
Labels: 🐛FIX
