Repository DDD-Community/DDD-10-KKEUNKKEUN-WEB, pull requests merged in 2024-01, with the labels that each got.

#3 [chore/add_husky_gitconfig] husky, lint-stage, gitconfig 설정
  .env
  .eslintignore
  .eslintrc.json
  .gitconfig
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.js
  .stylelintrc.json
  package-lock.json
  package.json
Labels: ⚙️CHORE

#5 로그인 페이지 초기 마크업 진행
  package-lock.json
  package.json
  src/app/(beforelogin)/landing/page.tsx
  src/app/(beforelogin)/layout.module.scss
  src/app/(beforelogin)/layout.tsx
  src/app/(beforelogin)/login/_components/Login.module.scss
  src/app/(beforelogin)/login/_components/Login.tsx
  src/app/(beforelogin)/login/_components/LoginForm.module.scss
  src/app/(beforelogin)/login/_components/LoginForm.tsx
  src/app/(beforelogin)/login/_components/LoginMenus.module.scss
  src/app/(beforelogin)/login/_components/LoginMenus.tsx
  src/app/(beforelogin)/login/_components/OAuthMenu.module.scss
  src/app/(beforelogin)/login/_components/OAuthMenu.tsx
  src/app/(beforelogin)/login/page.tsx
  src/app/(beforelogin)/page.tsx
  src/app/_components/_elements/Button.tsx
  src/app/_components/_elements/List.tsx
  src/app/_components/globals.scss
  src/app/globals.css
  src/types/common.ts
Labels: ✨FEAT

#6 공통 엘리먼트 타입 수정
  src/app/(afterlogin)/layout.tsx
  src/app/(beforelogin)/login/_components/LoginForm.tsx
  src/app/(beforelogin)/login/_components/LoginMenus.tsx
  src/app/(beforelogin)/login/_components/OAuthMenu.tsx
  src/app/_components/_elements/Button.tsx
  src/app/_components/_elements/Input.tsx
  src/app/_components/_elements/List.tsx
  src/types/common.ts
  src/types/element.ts
Labels: ♻️REFACTOR

#7 feat: QRcode, audio recording, image logic
  package-lock.json
  package.json
  src/app/(afterlogin)/practice/[id]/page.tsx
  src/app/(afterlogin)/practice/_components/Recorder.tsx
  src/app/_components/_modules/ImagePreview.tsx
  src/app/_components/_modules/ImageUploader.tsx
  src/app/_hooks/useImageUploader.ts
Labels: ✨FEAT

#8 발표 생성/수정 페이지 구현
  .eslintrc.json
  next.config.js
  package-lock.json
  package.json
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/CreatePresentation.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/EditPresentation.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/Spinner.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/Spinner.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadDday.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadDday.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_hooks/presentation.ts
  src/app/(afterlogin)/presentation/upload/[id]/_utils/getCurrentPageData.tsx
  src/app/(afterlogin)/presentation/upload/[id]/page.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/page.tsx
  src/app/(beforelogin)/login/_components/Login.module.scss
  src/app/_components/globals.scss
  src/app/api/get/list/[id]/route.ts
  src/app/globals.css
  src/services/user.ts
  src/types/service.ts
Labels: ✨FEAT

#9 checkbox, toggle button 컴포넌트 추가
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(beforelogin)/login/_components/LoginMenus.tsx
  src/app/(beforelogin)/login/_components/OAuthMenu.tsx
  src/app/_components/_elements/Button.tsx
  src/app/_components/_elements/Checkbox.tsx
  src/app/_components/_elements/Input.tsx
  src/app/_components/_elements/List.tsx
  src/app/_components/_elements/ToggleButton.module.scss
  src/app/_components/_elements/ToggleButton.tsx
  src/app/_utils/style.ts
  src/types/element.ts
Labels: ✨FEAT

#11 빌드 에러 수정 (route handler 반환 타입 명시)
  .husky/pre-push
  package-lock.json
  src/app/api/get/list/[id]/route.ts
Labels: 🐛FIX

#12 서버사이드 File객체 제거
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.tsx
  src/app/api/get/list/[id]/route.ts
Labels: 🐛FIX

#13 엘리먼트 타입 이름 수정 및 주석 추가 & 타임피커 컴포넌트 추가
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(beforelogin)/login/_components/LoginMenus.tsx
  src/app/(beforelogin)/login/_components/OAuthMenu.tsx
  src/app/_components/_elements/Button.tsx
  src/app/_components/_elements/Checkbox.tsx
  src/app/_components/_elements/Input.tsx
  src/app/_components/_elements/List.tsx
  src/app/_components/_elements/TimePicker.tsx
  src/app/_components/_elements/ToggleButton.tsx
  src/types/element.ts
Labels: ✨FEAT

#14 전역 모달 스토어 및 컴포넌트 생성
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/layout.tsx
  src/app/(afterlogin)/practice/_components/Recorder.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/presentation/upload/[id]/page.tsx
  src/app/(beforelogin)/login/_components/OAuthMenu.tsx
  src/app/_components/_elements/Checkbox.tsx
  src/app/_components/_elements/ToggleButton.tsx
  src/app/_components/_modules/AlertModal.module.scss
  src/app/_components/_modules/AlertModal.tsx
  src/app/_components/_modules/ConfirmModal.module.scss
  src/app/_components/_modules/ConfirmModal.tsx
  src/app/_components/_modules/ImagePreview.tsx
  src/app/_components/_modules/ImageUploader.tsx
  src/store/modal.ts
  src/types/element.ts
Labels: ✨FEAT

#15 토스트 컴포넌트 구현
  src/app/(afterlogin)/layout.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.tsx
  src/app/(beforelogin)/layout.module.scss
  src/app/_components/_modules/AlarmToast.module.scss
  src/app/_components/_modules/AlarmToast.tsx
  src/app/_components/_modules/AlertModal.module.scss
  src/app/_components/_modules/AlertModal.tsx
  src/app/_components/_modules/ConfirmModal.module.scss
  src/app/_components/_modules/ConfirmModal.tsx
  src/app/_components/_modules/SaveToast.module.scss
  src/app/_components/_modules/SaveToast.tsx
  src/app/_components/_modules/_modal/Modal.module.scss
  src/app/_components/_modules/_modal/Modal.tsx
  src/app/_components/_modules/_modal/Toast.module.scss
  src/app/_components/_modules/_modal/Toast.tsx
  src/store/modal.ts
Labels: ✨FEAT
