Repository DDD-Community/DDD-10-KKEUNKKEUN-WEB, pull requests merged in 2024-02, with the labels that each got.

#17 발표 업로드 페이지 유효성 검증, 캘린더 적용
  package-lock.json
  package.json
  src/app/(afterlogin)/presentation/upload/[id]/_component/CustomCalendar.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/CustomCalendar.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadDday.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadDday.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.tsx
  src/app/api/get/list/[id]/route.ts
  src/types/service.ts
Labels: ✨FEAT

#18 FlyoutMenu 컴포넌트 구현
  src/app/(afterlogin)/element-test/page.tsx
  src/app/_components/_modules/FlyoutMenu.module.scss
  src/app/_components/_modules/FlyoutMenu.tsx
  src/store/flyout.ts
  src/types/element.ts
Labels: ✨FEAT

#20 textarea 공통 컴포넌트 적용
  .stylelintrc.json
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.tsx
  src/app/_components/_elements/TextArea.module.scss
  src/app/_components/_elements/TextArea.tsx
  src/app/_components/globals.scss
  src/app/_components/mixins.scss
  src/types/element.ts
Labels: ✨FEAT

#21 Header 컴포넌트(Navbar) 마크업 생성
  src/app/(afterlogin)/_components/NavButtons.tsx
  src/app/(afterlogin)/_components/Navbar.module.scss
  src/app/(afterlogin)/_components/Navbar.tsx
  src/app/(afterlogin)/layout.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.tsx
Labels: ✨FEAT

#22 재사용 버튼 테마, 사이즈 구현
  src/app/(afterlogin)/_components/Navbar.module.scss
  src/app/(afterlogin)/element-test/page.module.scss
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/Spinner.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadDday.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/page.module.scss
  src/app/(beforelogin)/login/_components/Login.module.scss
  src/app/(beforelogin)/login/_components/LoginForm.module.scss
  src/app/(beforelogin)/login/_components/LoginMenus.module.scss
  src/app/(beforelogin)/login/_components/OAuthMenu.module.scss
  src/app/_components/_modules/AlertModal.module.scss
  src/app/_components/_modules/AlertModal.tsx
  src/app/_components/_modules/ConfirmModal.module.scss
  src/app/_components/_modules/ConfirmModal.tsx
  src/app/_components/_modules/_modal/Toast.module.scss
  src/app/_components/globals.scss
  src/app/_components/mixins.scss
Labels: ♻️REFACTOR, ✨FEAT

#24 발표 업로드 (생성/수정) 페이지 최종 디자인 및 유효성 적용
  .eslintrc.json
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadDday.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadScript.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.module.scss
  src/app/(afterlogin)/presentation/upload/[id]/_component/UploadTitle.tsx
  src/app/(afterlogin)/presentation/upload/[id]/_utils/getCurrentPageData.tsx
  src/app/(afterlogin)/upload/[id]/_component/ControlButtons.module.scss
  src/app/(afterlogin)/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/upload/[id]/_component/CreatePresentation.tsx
  src/app/(afterlogin)/upload/[id]/_component/CustomCalendar.scss
  src/app/(afterlogin)/upload/[id]/_component/CustomCalendar.tsx
  src/app/(afterlogin)/upload/[id]/_component/EditPresentation.tsx
  src/app/(afterlogin)/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/upload/[id]/_component/Required.tsx
  src/app/(afterlogin)/upload/[id]/_component/Spinner.module.scss
  src/app/(afterlogin)/upload/[id]/_component/Spinner.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadDday.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadDday.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadMemo.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadScript.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadTimer.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadTitle.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadTitle.tsx
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.ts
  src/app/(afterlogin)/upload/[id]/_utils/date.ts
  src/app/(afterlogin)/upload/[id]/_utils/validation.ts
  src/app/(afterlogin)/upload/[id]/page.module.scss
  src/app/(afterlogin)/upload/[id]/page.tsx
  src/app/_components/_modules/AlertModal.module.scss
  src/app/_components/_modules/ConfirmModal.module.scss
  src/app/_components/_modules/SaveToast.module.scss
  src/app/_components/_modules/SaveToast.tsx
  src/app/_components/_modules/_modal/ModalContents.module.scss
  src/app/_components/_modules/_modal/ModalContents.tsx
  src/app/_components/_modules/_modal/Toast.tsx
  src/app/_components/_svgs/InputFormSvgs.module.scss
  src/app/_components/_svgs/InputFormSvgs.tsx
  src/app/_components/_svgs/PptImgSvgs.tsx
  src/app/api/get/list/[id]/route.ts
  src/config/const.ts
  src/store/modal.ts
  src/types/service.ts
Labels: ♻️REFACTOR, ✨FEAT

#25 발표 목록 페이지 UI 작업
  src/app/(afterlogin)/_components/Navbar.module.scss
  src/app/(afterlogin)/home/_components/ExerciseItem.module.scss
  src/app/(afterlogin)/home/_components/ExerciseItem.tsx
  src/app/(afterlogin)/home/_components/ExerciseList.module.scss
  src/app/(afterlogin)/home/_components/ExerciseList.tsx
  src/app/(afterlogin)/home/_components/ExerciseMenu.tsx
  src/app/(afterlogin)/home/_components/HistoryBanner.module.scss
  src/app/(afterlogin)/home/_components/HistoryBanner.tsx
  src/app/(afterlogin)/home/_components/_elements/ExerciseInfo.module.scss
  src/app/(afterlogin)/home/_components/_elements/ExerciseInfo.tsx
  src/app/(afterlogin)/home/_components/_svgs/DeleteIcon.tsx
  src/app/(afterlogin)/home/_components/_svgs/MenuIcon.tsx
  src/app/(afterlogin)/home/_components/_svgs/ModifyIcon.tsx
  src/app/(afterlogin)/home/_components/_svgs/PlusIcon.tsx
  src/app/(afterlogin)/home/page.module.scss
  src/app/(afterlogin)/home/page.tsx
  src/app/_components/_modules/FlyoutMenu.module.scss
  src/app/_components/_modules/FlyoutMenu.tsx
  src/styles/globals.scss
  src/styles/mixins.scss
Labels: ✨FEAT

#26 발표 추가 및 수정 페이지 유효성 로직 변경, 시간 단위 수정, 글꼴 추가
  src/app/(afterlogin)/_components/RQProvider.tsx
  src/app/(afterlogin)/element-test/page.module.scss
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/home/_components/ExerciseList.tsx
  src/app/(afterlogin)/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/upload/[id]/_component/InputSection.module.scss
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadDday.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadScript.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadTimer.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadTitle.tsx
  src/app/(afterlogin)/upload/[id]/_component/_svgs/InputFormSvgs.module.scss
  src/app/(afterlogin)/upload/[id]/_component/_svgs/InputFormSvgs.tsx
  src/app/(afterlogin)/upload/[id]/_component/_svgs/PptImgSvgs.tsx
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.ts
  src/app/_components/_modules/SaveToast.module.scss
  src/app/_components/_svgs/InputFormSvgs.module.scss
  src/app/_components/_svgs/InputFormSvgs.tsx
  src/app/globals.css
  src/config/const.ts
  src/services/user.ts
  src/styles/mixins.scss
Labels: ♻️REFACTOR, ✨FEAT

#27 디자인 변경 사항 반영 (nav 컴포넌트, 컬러 및 폰트 변수)
  src/app/(afterlogin)/_components/NavMenu.tsx
  src/app/(afterlogin)/_components/Navbar.module.scss
  src/app/(afterlogin)/_components/Navbar.tsx
  src/app/(afterlogin)/_svgs/UserIcon.tsx
  src/app/(afterlogin)/home/_components/ExerciseItem.module.scss
  src/app/(afterlogin)/home/_components/ExerciseList.module.scss
  src/app/(afterlogin)/home/_components/HistoryBanner.module.scss
  src/app/(afterlogin)/home/_components/_elements/ExerciseInfo.module.scss
  src/app/(afterlogin)/home/layout.tsx
  src/app/(afterlogin)/layout.tsx
  src/app/(afterlogin)/practice/layout.tsx
  src/app/(afterlogin)/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadScript.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/upload/[id]/_svgs/InputFormSvgs.module.scss
  src/app/(afterlogin)/upload/[id]/_svgs/InputFormSvgs.tsx
  src/app/(afterlogin)/upload/[id]/_svgs/PptImgSvgs.tsx
  src/app/(afterlogin)/upload/[id]/layout.tsx
  src/app/_components/_modules/SaveToast.module.scss
  src/app/_svgs/LogoIcon.tsx
  src/styles/globals.scss
  src/styles/mixins.scss
Labels: ♻️REFACTOR

#28 변경된 디자인 반영
  src/app/(afterlogin)/_components/Navbar.tsx
  src/app/(afterlogin)/home/_components/ExerciseList.module.scss
  src/app/(afterlogin)/home/_components/ExerciseList.tsx
  src/app/(afterlogin)/home/_components/HistoryBanner.module.scss
  src/app/(afterlogin)/home/_components/HistoryBanner.tsx
  src/app/_svgs/LogoIcon.tsx
  src/app/globals.css
Labels: ♻️REFACTOR

#29 소셜 로그인 및 자동화 구현 - 카카오
  next.config.js
  src/app/(afterlogin)/_components/NavMenu.tsx
  src/app/(afterlogin)/_components/Navbar.tsx
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/error.tsx
  src/app/(afterlogin)/upload/[id]/_component/Spinner.tsx
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.ts
  src/app/(afterlogin)/upload/[id]/_svgs/PptImgSvgs.tsx
  src/app/(afterlogin)/upload/[id]/page.tsx
  src/app/(beforelogin)/accounts/login/process/_components/GetToken.tsx
  src/app/(beforelogin)/accounts/login/process/page.tsx
  src/app/(beforelogin)/login/_components/Login.module.scss
  src/app/(beforelogin)/login/_components/Login.tsx
  src/app/(beforelogin)/login/_components/LoginForm.module.scss
  src/app/(beforelogin)/login/_components/LoginForm.tsx
  src/app/(beforelogin)/login/_components/LoginMenus.module.scss
  src/app/(beforelogin)/login/_components/LoginMenus.tsx
  src/app/(beforelogin)/login/_components/OAuthMenu.module.scss
  src/app/(beforelogin)/login/_components/OAuthMenu.tsx
  src/app/(beforelogin)/login/_components/SocialLoginButtons.module.scss
  src/app/(beforelogin)/login/_components/SocialLoginButtons.tsx
  src/app/(beforelogin)/login/_svgs/SocialLogoIcon.tsx
  src/app/(beforelogin)/login/page.module.scss
  src/app/(beforelogin)/login/page.tsx
  src/app/_components/AuthSession.tsx
  src/app/_components/_modules/Spinner.module.scss
  src/app/_components/_modules/Spinner.tsx
  src/app/_svgs/LogoIcon.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/get/auth/kakao/route.ts
  src/app/api/get/auth/slient/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/auth.ts
  src/config/const.ts
  src/config/path.ts
  src/middleware.ts
  src/services/client/fetchClient.ts
  src/services/client/user.ts
  src/services/server/fetchServer.ts
  src/services/server/user.ts
  src/store/user.ts
  src/styles/globals.scss
  src/types/service.ts
Labels: ♻️REFACTOR, ✨FEAT

#30 발표 세팅 페이지 마크업 구현
  package-lock.json
  package.json
  src/app/(afterlogin)/setting/[id]/_components/Card.module.scss
  src/app/(afterlogin)/setting/[id]/_components/Card.tsx
  src/app/(afterlogin)/setting/[id]/_components/DragSection.scss
  src/app/(afterlogin)/setting/[id]/_components/DragSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/HighlightButton.tsx
  src/app/(afterlogin)/setting/[id]/_components/RemoveButton.tsx
  src/app/(afterlogin)/setting/[id]/_components/SelectCardSection.module.scss
  src/app/(afterlogin)/setting/[id]/_components/SelectCardSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/SelectSentenceSection.module.scss
  src/app/(afterlogin)/setting/[id]/_components/SelectSentenceSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/SettingProcess.module.scss
  src/app/(afterlogin)/setting/[id]/_components/SettingProcess.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepNumbers.module.scss
  src/app/(afterlogin)/setting/[id]/_components/StepNumbers.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepsBar.module.scss
  src/app/(afterlogin)/setting/[id]/_components/StepsBar.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepsContent.module.scss
  src/app/(afterlogin)/setting/[id]/_components/StepsContent.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepsDescription.module.scss
  src/app/(afterlogin)/setting/[id]/_components/StepsDescription.tsx
  src/app/(afterlogin)/setting/[id]/page.module.scss
  src/app/(afterlogin)/setting/[id]/page.tsx
  src/app/globals.css
Labels: ✨FEAT

#31 모달 컴포넌트 리뉴얼
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/layout.tsx
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/_components/_elements/Switch.module.scss
  src/app/_components/_elements/Switch.tsx
  src/app/_components/_modules/_modal-pre/Modal.module.scss
  src/app/_components/_modules/_modal-pre/Modal.tsx
  src/app/_components/_modules/_modal-pre/ModalContents.module.scss
  src/app/_components/_modules/_modal-pre/ModalContents.tsx
  src/app/_components/_modules/_modal-pre/Toast.module.scss
  src/app/_components/_modules/_modal-pre/Toast.tsx
  src/app/_components/_modules/_modal/Alert.module.scss
  src/app/_components/_modules/_modal/Alert.tsx
  src/app/_components/_modules/_modal/Confirm.module.scss
  src/app/_components/_modules/_modal/Confirm.tsx
  src/app/_components/_modules/_modal/Modal.module.scss
  src/app/_components/_modules/_modal/Modal.tsx
  src/app/_components/_modules/_modal/ModalLayout.module.scss
  src/app/_components/_modules/_modal/ModalLayout.tsx
  src/app/_hooks/useToggle.ts
  src/app/_hooks/useToggleContext.ts
  src/app/_svgs/CloseIcon.tsx
  src/types/element.ts
Labels: ♻️REFACTOR, ✨FEAT

#32 발표 추가 및 생성 페이지 백엔드 api 연동 및 버그 수정,
  next.config.js
  src/app/(afterlogin)/_components/Navbar.module.scss
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/upload/[id]/_component/CreatePresentation.tsx
  src/app/(afterlogin)/upload/[id]/_component/EditPresentation.tsx
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadDday.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadDeadlineDate.module.scss
  src/app/(afterlogin)/upload/[id]/_component/UploadDeadlineDate.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadMemo.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadScript.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadTimer.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadTitle.tsx
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.ts
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.tsx
  src/app/(afterlogin)/upload/[id]/_svgs/InputFormSvgs.tsx
  src/app/(afterlogin)/upload/[id]/_utils/validation.ts
  src/app/(afterlogin)/upload/[id]/page.tsx
  src/app/_components/_modules/_modal/Confirm.module.scss
  src/app/_components/_modules/_modal/Confirm.tsx
  src/app/_components/_modules/_modal/ModalLayout.module.scss
  src/app/api/get/auth/slient/route.ts
  src/app/api/get/list/[id]/route.ts
  src/config/const.ts
  src/services/client/fetchClient.ts
  src/services/client/upload.ts
  src/services/client/user.ts
  src/types/service.ts
Labels: 🐛FIX, ✨FEAT

#33 발표 연습 페이지 UI 및 녹음 관련 기능
  src/app/(afterlogin)/element-test/page.tsx
  src/app/(afterlogin)/practice/[id]/page.module.scss
  src/app/(afterlogin)/practice/[id]/page.tsx
  src/app/(afterlogin)/practice/_components/PracticeNav.module.scss
  src/app/(afterlogin)/practice/_components/PracticeNav.tsx
  src/app/(afterlogin)/practice/_hooks/useRecorder.ts
  src/app/(afterlogin)/practice/_svgs/CloseIcon.tsx
  src/app/(afterlogin)/practice/_svgs/RecordOnIcon.tsx
  src/app/(afterlogin)/practice/layout.tsx
  src/app/_components/_modules/SpeechBubble.module.scss
  src/app/_components/_modules/SpeechBubble.tsx
  src/app/_components/_modules/_modal/Alert.tsx
  src/app/_components/_modules/_modal/Confirm.tsx
  src/app/_components/_modules/_modal/Modal.module.scss
  src/app/_components/_modules/_modal/Modal.tsx
  src/app/_svgs/CloseIcon.tsx
Labels: ♻️REFACTOR, ✨FEAT

#34 발표 연습 시작 전 설정 페이지 백엔드 api 연동
  src/app/(afterlogin)/practice/_components/PracticeNav.tsx
  src/app/(afterlogin)/setting/[id]/_components/CancelButton.tsx
  src/app/(afterlogin)/setting/[id]/_components/Card.tsx
  src/app/(afterlogin)/setting/[id]/_components/DragSection.scss
  src/app/(afterlogin)/setting/[id]/_components/DragSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/HighlightButton.tsx
  src/app/(afterlogin)/setting/[id]/_components/RemoveButton.tsx
  src/app/(afterlogin)/setting/[id]/_components/SelectCardSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/SelectSentenceSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/SettingNav.module.scss
  src/app/(afterlogin)/setting/[id]/_components/SettingNav.tsx
  src/app/(afterlogin)/setting/[id]/_components/SettingProcess.module.scss
  src/app/(afterlogin)/setting/[id]/_components/SettingProcess.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepNumbers.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepsBar.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepsContent.tsx
  src/app/(afterlogin)/setting/[id]/_components/StepsDescription.tsx
  src/app/(afterlogin)/setting/[id]/_components/ToolbarButtons.module.scss
  src/app/(afterlogin)/setting/[id]/_components/_svgs/PenIcon.tsx
  src/app/(afterlogin)/setting/[id]/_components/_svgs/TrashcanIcon.tsx
  src/app/(afterlogin)/setting/[id]/_hooks/draft.ts
  src/app/(afterlogin)/setting/[id]/_hooks/settingInfo.ts
  src/app/(afterlogin)/setting/[id]/layout.module.scss
  src/app/(afterlogin)/setting/[id]/layout.tsx
  src/app/(afterlogin)/setting/[id]/page.module.scss
  src/app/(afterlogin)/setting/[id]/page.tsx
  src/app/(afterlogin)/upload/[id]/_component/InputSection.tsx
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.tsx
  src/app/_components/_modules/SpeechBubble.tsx
  src/app/_components/_modules/_modal/Confirm.tsx
  src/app/_components/_modules/_modal/Modal.tsx
  src/app/_svgs/CloseIconBlack.tsx
  src/app/_svgs/CloseIconWhite.tsx
  src/services/client/setting.ts
  src/services/client/upload.ts
  src/services/server/setting.ts
  src/types/service.ts
Labels: ✨FEAT

#35 발표 목록 삭제 컴펌 노출하도록 로직 추가
  src/app/(afterlogin)/home/_components/ExerciseItem.module.scss
  src/app/(afterlogin)/home/_components/ExerciseItem.tsx
  src/app/(afterlogin)/home/_components/ExerciseList.module.scss
  src/app/(afterlogin)/home/_components/ExerciseList.tsx
  src/app/(afterlogin)/home/page.tsx
  src/app/_components/_modules/FlyoutMenu.tsx
Labels: ♻️REFACTOR, ✨FEAT

#36 발표 생성 페이지 중복 post 오류 수정, CDN baseUrl 환경변수 적용
  src/app/(afterlogin)/setting/[id]/_components/SelectSentenceSection.tsx
  src/app/(afterlogin)/setting/[id]/_components/SettingProcess.tsx
  src/app/(afterlogin)/upload/[id]/_component/ControlButtons.tsx
  src/app/(afterlogin)/upload/[id]/_component/UploadPpt.tsx
  src/app/(afterlogin)/upload/[id]/_hooks/presentation.tsx
  src/types/service.ts
Labels: ⚙️CHORE, 🐛FIX

#37 feat: 랜딩 페이지 마크업 구현(SVG제외)
  src/app/(beforelogin)/layout.module.scss
  src/app/(beforelogin)/layout.tsx
  src/app/(beforelogin)/page.module.scss
  src/app/(beforelogin)/page.tsx
Labels: ✨FEAT
